server:
  port: 8008

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        default_batch_fetch_size: 100
        jdbc:
          time_zone: Asia/Seoul

externals:
  letsur:
    base-url: https://ggsapi.gugus.co.kr/api
    api-key: ${LETSUR_API_KEY}
    endpoints:
      brands: /v1/externals/letsur/brand
      categories: /v1/externals/letsur/category
      management-models: /v1/externals/letsur/management-models
      appraisal-points: /v1/externals/letsur/appraisal-point
      goods: /v1/externals/letsur/goods/image-search

sync:
  common:
    zone: Asia/Seoul
  # 통합 스케줄러 - 운영 시 사용
  fullsync:
    enabled: true
    cron: "0 0 1 * * *"
  # 개별 스케줄러 - 운영 시 미사용
  category:
    enabled: false
    cron: "0 5 2 * * *"
    page-size: 200
  brand:
    enabled: false
    cron: "0 20 2 * * *"
    page-size: 200
  model:
    enabled: false
    cron: "0 30 2 * * *"
    page-size: 200
  appraisal-point:
    enabled: false
    cron: "0 40 2 * * *"
    page-size: 200
  goods:
    enabled: false
    cron: "0 30 3 * * *"
    page-size: 200
