spring:
  datasource:
    url: jdbc:mysql://prod-db-server:3306/gugus_prod?useSSL=false&characterEncoding=utf-8
    username: root
    password: prod123
    hikari:
      maximum-pool-size: 10
      pool-name: prod-gugus-db-pool
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: false
