spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    hikari:
      maximum-pool-size: 3
      pool-name: stage-gugus-db-pool
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: false
